language: android
jdk: oraclejdk8
android:
components:
- tools
- build-tools-26.0.2
- android-26
- extra-android-m2repository
- extra-android-support
licenses:
- 'android-sdk-preview-license-52d11cd2'
- 'android-sdk-license-.+'
- 'google-gdk-license-.+'
notifications:
email: false
before_install:
- chmod +x gradlew
- mkdir -p "$ANDROID_HOME/licenses"
- echo -e "\8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- sdkmanager --licenses
script: ./gradlew clean build
