language: android
jdk: oraclejdk8
android:
components:
- tools
- build-tools-25.0.0
- android-25
- extra-android-m2repository
- extra-android-support
- mkdir -p "$ANDROID_HOME/licenses"
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
notifications:
email: false
before_install:
- chmod +x gradlew
script: ./gradlew clean
